version: '3'

services:
  server:
    build: ./server
    ports:
      - "50051:50051"
    networks:
      - grpc-net

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge
